// Package emoji provides a fallback mapper from Unicode emoji to :shortcode: text.
// Activated via the --no-emoji CLI flag; no terminal introspection is performed.
package emoji

import "strings"

// MapString replaces emoji runes in s with their :shortcode: equivalents when
// noEmoji is true. When noEmoji is false the string is returned unchanged.
func MapString(s string, noEmoji bool) string {
	if !noEmoji {
		return s
	}
	var b strings.Builder
	for _, r := range s {
		if code, ok := shortcodes[r]; ok {
			b.WriteString(":")
			b.WriteString(code)
			b.WriteString(":")
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// shortcodes maps common emoji runes to their shortcode names.
var shortcodes = map[rune]string{
	// Faces
	'😀': "grinning",
	'😁': "beaming",
	'😂': "joy",
	'🤣': "rofl",
	'😃': "smiley",
	'😄': "smile",
	'😅': "sweat_smile",
	'😆': "laughing",
	'😉': "wink",
	'😊': "blush",
	'😋': "yum",
	'😎': "sunglasses",
	'😍': "heart_eyes",
	'🥰': "smiling_face_with_hearts",
	'😘': "kissing_heart",
	'🙂': "slightly_smiling",
	'🤗': "hugs",
	'🤔': "thinking",
	'😐': "neutral_face",
	'😑': "expressionless",
	'😶': "no_mouth",
	'😏': "smirk",
	'😒': "unamused",
	'🙄': "eye_roll",
	'😬': "grimacing",
	'😌': "relieved",
	'😔': "pensive",
	'😪': "sleepy",
	'😴': "sleeping",
	'😷': "mask",
	'🤢': "nauseated",
	'🤧': "sneezing",
	'🥵': "hot_face",
	'🥶': "cold_face",
	'😡': "rage",
	'😠': "angry",
	'😭': "sob",
	'😢': "cry",
	'😱': "scream",
	'😳': "flushed",
	'🥺': "pleading",
	'😞': "disappointed",
	'😩': "weary",
	'🤯': "exploding_head",
	'🥳': "partying",
	'🧐': "monocle",
	'🤓': "nerd",
	'😈': "smiling_imp",
	'👿': "imp",
	'💀': "skull",
	'💩': "poop",
	'🤖': "robot",
	'👻': "ghost",
	'👽': "alien",
	// Hands & people
	'👋': "wave",
	'✋': "raised_hand",
	'👌': "ok_hand",
	'✌':  "v",
	'🤞': "crossed_fingers",
	'🤘': "metal",
	'👈': "point_left",
	'👉': "point_right",
	'👆': "point_up_2",
	'👇': "point_down",
	'👍': "thumbsup",
	'👎': "thumbsdown",
	'✊': "fist",
	'👊': "punch",
	'👏': "clap",
	'🙌': "raised_hands",
	'🙏': "pray",
	// Hearts
	'❤':  "heart",
	'🧡': "orange_heart",
	'💛': "yellow_heart",
	'💚': "green_heart",
	'💙': "blue_heart",
	'💜': "purple_heart",
	'🖤': "black_heart",
	'💔': "broken_heart",
	'💕': "two_hearts",
	'💖': "sparkling_heart",
	// Nature & weather
	'🔥': "fire",
	'💧': "droplet",
	'🌊': "ocean",
	'⭐': "star",
	'🌟': "star2",
	'✨': "sparkles",
	'⚡': "zap",
	'🌈': "rainbow",
	'☀':  "sunny",
	'❄':  "snowflake",
	'🌙': "crescent_moon",
	'🌸': "cherry_blossom",
	'🌹': "rose",
	'🍀': "four_leaf_clover",
	// Animals
	'🐶': "dog",
	'🐱': "cat",
	'🐭': "mouse",
	'🐰': "rabbit",
	'🦊': "fox",
	'🐻': "bear",
	'🐼': "panda",
	'🐯': "tiger",
	'🦁': "lion",
	'🐮': "cow",
	'🐷': "pig",
	'🐸': "frog",
	'🐵': "monkey",
	'🙈': "see_no_evil",
	'🙉': "hear_no_evil",
	'🙊': "speak_no_evil",
	'🐧': "penguin",
	'🦋': "butterfly",
	'🐝': "bee",
	'🦄': "unicorn",
	// Food & drink
	'🍕': "pizza",
	'🍔': "hamburger",
	'🌮': "taco",
	'🍜': "ramen",
	'🍣': "sushi",
	'🍰': "cake",
	'🎂': "birthday",
	'🍺': "beer",
	'🍻': "beers",
	'☕': "coffee",
	'🍵': "tea",
	'🍎': "apple",
	'🍌': "banana",
	'🍓': "strawberry",
	// Objects
	'📱': "iphone",
	'💻': "computer",
	'📷': "camera",
	'📞': "telephone_receiver",
	'💡': "bulb",
	'🔑': "key",
	'🔒': "lock",
	'🔓': "unlock",
	'🔨': "hammer",
	'🔧': "wrench",
	'📌': "pushpin",
	'📎': "paperclip",
	'✂':  "scissors",
	'📝': "memo",
	'📚': "books",
	'📖': "book",
	'📧': "email",
	'💰': "moneybag",
	'💎': "gem",
	'🔍': "mag",
	// Symbols
	'✅': "white_check_mark",
	'❌': "x",
	'➕': "heavy_plus_sign",
	'➖': "heavy_minus_sign",
	'💯': "100",
	'🔴': "red_circle",
	'🟢': "green_circle",
	'🔵': "blue_circle",
	'⚫': "black_circle",
	'⚪': "white_circle",
	// Activities & travel
	'🎉': "tada",
	'🎊': "confetti",
	'🎈': "balloon",
	'🎁': "gift",
	'🏆': "trophy",
	'🎮': "video_game",
	'🎨': "art",
	'🎵': "musical_note",
	'🎶': "notes",
	'🚀': "rocket",
	'✈':  "airplane",
	'🚗': "car",
	'🏠': "house",
	'🗺': "world_map",
	'🏖': "beach",
	'⛺': "tent",
}
