# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WapCli < Formula
  desc "Minimal WhatsApp CLI for the terminal"
  homepage "https://github.com/ana-rodrigues/wap"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ana-rodrigues/wap/releases/download/v0.1.1/wap_0.1.1_darwin_amd64.tar.gz"
      sha256 "6a622585a9e0013428e4007b1cea1b84691e553492160f53773752ede9757dbe"

      define_method(:install) do
        bin.install "wap-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ana-rodrigues/wap/releases/download/v0.1.1/wap_0.1.1_darwin_arm64.tar.gz"
      sha256 "a8be2cc37259230f07714f39e08b7ec959e5e4ccc1086efb5e6beba0e1101ebc"

      define_method(:install) do
        bin.install "wap-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ana-rodrigues/wap/releases/download/v0.1.1/wap_0.1.1_linux_amd64.tar.gz"
      sha256 "685f171853921f212f4634b970c5554ac41f075b02038ff94d01664a040962d7"
      define_method(:install) do
        bin.install "wap-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ana-rodrigues/wap/releases/download/v0.1.1/wap_0.1.1_linux_arm64.tar.gz"
      sha256 "d06ccd2a7cad859ee328eae1d73d813cb86c687d6535ecc70cb8c329cffb9f4b"
      define_method(:install) do
        bin.install "wap-cli"
      end
    end
  end
end
