# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WapCli < Formula
  desc "Minimal WhatsApp CLI for the terminal"
  homepage "https://github.com/ana-rodrigues/wap"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ana-rodrigues/wap/releases/download/v0.1.0/wap_0.1.0_darwin_amd64.tar.gz"
      sha256 "c9118f4f51b48ed8944fc4788d43d41c5efa450ee0800ecc9dcb223b9f2c701a"

      define_method(:install) do
        bin.install "wap-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ana-rodrigues/wap/releases/download/v0.1.0/wap_0.1.0_darwin_arm64.tar.gz"
      sha256 "51d3ba55f20bbd54929d23a22b4bcbb9aae8f318f4b31c0c0af41b8a0dd2cd3a"

      define_method(:install) do
        bin.install "wap-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ana-rodrigues/wap/releases/download/v0.1.0/wap_0.1.0_linux_amd64.tar.gz"
      sha256 "82001e1bb7eae4628dda6bb2017b6cea0fa8652cf58cb052cb30719006a7e163"
      define_method(:install) do
        bin.install "wap-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ana-rodrigues/wap/releases/download/v0.1.0/wap_0.1.0_linux_arm64.tar.gz"
      sha256 "6e59b2f0855f0496bf8da5425f3fc2e53c9679a5eadad5bfc902aa13c11e0ae1"
      define_method(:install) do
        bin.install "wap-cli"
      end
    end
  end
end
